
create table CourseRegistration( 
    email char(40) primary key,
    phone int not null unique, 
    center char(20) not null, 
    district char(20) not null, 
    name char(30) not null, 
    father_name char(30) not null, 
    mother_name char(30) not null, 
    address varchar(100) not null, 
    ration_number char(20) not null, 
    aadhaar_number int not null unique, 
    religion char(10) not null,
    community char(3) not null, 
    caste char(15) not null, 
    gender char(6) not null, 
    dob date not null, 
    eighth char(4) not null, 
    tenth char(4) not null, 
    diplomo char(10) not null, 
    degree char(10) not null, 
    tamil_medium char(3) not null, 
    height int not null, 
    weight int not null, 
    license_number char(20) not null unique, 
    license_issue_date date not null, 
    license_expire_date date not null, 
    badge_number char(20) not null, 
    badge_issue_date date not null, 
    psv_region char(20) not null, 
    hptv_issue_date date not null,
    passbook_details varchar(100) not null, 
    free_courses char(3) not null
    ); 
